### ISSUE TITLE
Zooming on Huge Images (Resolution loss)

### ISSUE THREAD

**Issue by RangerHalt** [vgilabert94/streamlit-image-zoom#2]
Hey, great work on this, came just in time for something I'm working on! ;)

One issue I have:, and maybe I'm just using this wrong, or hopefully it's an easy fix:

I have really large images I want to display (10,00s x 10,000s).

If I do not set the `size` argument, the image is displayed in full size, and obviously does not fit in the web browser.

If I set `size` to something that would fit on the screen, zoomed out looks perfect, but if I zoom in, the zoom is done on the downsampled version of the image, so resolution is lost, and things are really pixelated.

Is it possible to have some sort of size parameter that rescales the image to the "viewable" image, but stores the full resolution image and performs zooming on that, so resolution is not lost when zooming in?

Hopefully my explanation made sense, please let me know if you need me to rephrase anything.

**Comment by vgilabert94** [comment]
That's a good point, for now that loss of resolution is how the app works but I like the idea of adding a `keep_resolution` parameter to show in the zoomed image the original resolution. I will review to add this option.

Another thing is if you don't set any` size`, it defaults to 512, so it will show at that size, not the original. Could be fine if size is `None` use the original size of the image, but for now you can directly pass the original size as the size parameter... But the most normal thing is that not fit in the web browser.

**Comment by RangerHalt** [comment]
>  ...works but I like the idea of adding a `keep_resolution` parameter to show in the zoomed image the original resolution. I will review to add this option.

That would be great, thank you very much!

> Another thing is if you don't set any size, it defaults to 512...

Yes, you're right, sorry I misspoke. When I give it a size that can fit in the window (or omit and use the default), zooming in loses the resolution, and when I entered the full size of the image, the full image was displayed, which was way too big to fit in the browser.
