### ISSUE TITLE
Option to drag and move image 

### ISSUE THREAD

**Issue by talrejanikhil** [vgilabert94/streamlit-image-zoom#6]
Is it possible to add an option to Drag and move the zoomed image instead of using mouse movements?

**Comment by vgilabert94** [comment]
Send me an example of exactly what you are talking about and I can review it.

**Comment by talrejanikhil** [comment]
If you go here https://www.saturn.de/de/product/_xiaomi-mi-scooter-4-pro-e-scooter-10-zoll-black-2919706.html and open the image in full screen. You can click on the image to zoom and then drag the mouse to move the zoomed image. 
So instead of the mousemove action, we use the drag action to move the zoomed image. 

The problem with mouse move is that the zoomed image moves when you move the mouse in any direction which is not always desirable since sometimes we want to just zoom into a specific part of the image and then leave it there to read the text on the image

**Comment by vgilabert94** [comment]
Update to new version (0.0.4) that include the drag and move zoom. 

How it works:
"Drag and move mode Single-click to zoom in, click and drag to move the zoomed image, and double-click to zoom out."
